name: Publish native binaries

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  buildOnLinux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew :yaml-config-updater-cli:shadowJar :yaml-config-updater-cli:nativeImage --no-daemon

      - name: Rename files
        run: |
          mkdir upload
          cp yaml-config-updater-cli/build/libs/*-all.jar upload/yaml-updater.jar
          cp yaml-config-updater-cli/build/graal/* upload/yaml-updater-linux-amd64

      - name: Run UPX
        uses: crazy-max/ghaction-upx@v1.4.0
        with:
          version: latest
          files: ./upload/yaml-updater-linux-amd64
          args: '--lzma --best'

#      - name: Attach to release
#        uses: softprops/action-gh-release@v1
#        with:
#          files: |
#            upload/yaml-updater.jar
#            upload/yaml-updater-linux-amd64


  buildOnWindows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Setup MS dev tools
        uses: ilammy/msvc-dev-cmd@v1.10.0

      - name: Setup MS VS tools
        uses: microsoft/setup-msbuild@v1.1.1
        with:
          msbuild-architecture: x64

      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew :yaml-config-updater-cli:nativeImage --no-daemon

      - name: Rename files
        run: |
          mkdir upload
          cp yaml-config-updater-cli/build/graal/* ./upload/yaml-updater.exe

      - name: Run UPX
        uses: crazy-max/ghaction-upx@v1.4.0
        with:
          version: latest
          files: ./upload/yaml-updater.exe
          args: '--lzma --best'

#      - name: Attach to release
#        uses: softprops/action-gh-release@v1
#        with:
#          files: upload/yaml-updater.exe

  buildOnMac:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew :yaml-config-updater-cli:nativeImage --no-daemon

      - name: Rename files
        run: |
          mkdir upload
          cp yaml-config-updater-cli/build/graal/* upload/yaml-updater-mac-amd64

      - name: Run UPX
        uses: svenstaro/upx-action@v2
        with:
          file: ./upload/yaml-updater-mac-amd64
          args: '--lzma --best'

#      - name: Attach to release
#        uses: softprops/action-gh-release@v1
#        with:
#          files: upload/yaml-updater-mac-amd64
