name: Publish native binaries

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  buildOnLinux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew :yaml-config-updater-cli:shadowJar :yaml-config-updater-cli:nativeImage --no-daemon

      - name: Rename files
        run: |
          mkdir upload
          cp yaml-config-updater-cli/build/libs/*-all.jar upload/yaml-updater.jar
          cp yaml-config-updater-cli/build/graal/* upload/yaml-updater-linux

      - name: Run UPX
        uses: crazy-max/ghaction-upx@v1.4.0
        with:
          version: latest
          file: upload/yaml-updater-linux-amd64
          args: '-7'

#      - name: Upload jar
#        uses: JasonEtco/upload-to-release@master
#        with:
#          args: upload/yaml-updater.jar
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#
#      - name: Upload linux binary
#        uses: JasonEtco/upload-to-release@master
#        with:
#          args: upload/yaml-updater-linux-amd64
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  buildOnWindows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Setup MS dev tools
        uses: ilammy/msvc-dev-cmd@v1.10.0

      - name: Setup MS VS tools
        uses: microsoft/setup-msbuild@v1

      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew :yaml-config-updater-cli:nativeImage --no-daemon

      - name: Rename files
        run: |
          mkdir upload
          cp yaml-config-updater-cli/build/graal/* upload/yaml-updater.exe

      - name: Run UPX
        uses: crazy-max/ghaction-upx@v1.4.0
        with:
          version: latest
          file: upload/yaml-updater.exe
          args: '-7'

#      - name: Upload windows binary
#        uses: JasonEtco/upload-to-release@master
#        with:
#          args: upload/yaml-updater.exe
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  buildOnMac:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew :yaml-config-updater-cli:nativeImage --no-daemon

      - name: Rename files
        run: |
          mkdir upload
          cp yaml-config-updater-cli/build/graal/* upload/yaml-updater-mac-amd64

      - name: Run UPX
        uses: svenstaro/upx-action@v2
        with:
          file: upload/yaml-updater-mac-amd-64
          args: '-7'

#      - name: Upload mac binary
#        uses: JasonEtco/upload-to-release@master
#        with:
#          args: upload/yaml-updater-mac-amd64
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}